config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'classrooms#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :missions, only: %i[edit update destroy] do
    resources :mission_setups, only: %i[create index update]
  end

  resources :classrooms, only: [:show] do
    resources :students, only: %i[index new create]
    resources :missions, only: %i[new create index]
  end

  resources :mission_setups do
    collection do
      match "update_collection", via: %i[put patch]
    end
  end

  resources :students, only: %i[show update]
  resources :rewards, only: %i[index show new create destroy] do
    resources :reward_transactions, only: %i[create show index]
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom
  has_one_attached :photo

  has_many :missions, through: :mission_setups

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true

  def name
    first_name
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
    @classroom = Classroom.find(params[:classroom_id])
  end

  def create
    @student = Student.new(student_params)
    @classroom = Classroom.find(params[:classroom_id])
    @student.classroom = @classroom
    if @student.save
      redirect_to classroom_students_path(@classroom)
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
    @my_missions_completed = []
    @my_missions = MissionSetup.where(student_id: @student.id)
    @my_missions.each do |m|
      if m.completion == true
        @my_missions_completed << Mission.find(m.mission_id)
      end
    end
  end

  def update
    @student = Student.find(params[:id])
    @coins = @student.coins
    if params[:value] == "add"
      @student.update(coins: @coins += 1)
    else
      @student.update(coins: @coins -= 1)
    end
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :date_of_birth, :coins, :photo)
  end
end

app/views/students/index.html.erb
<h1> My Classroom</h1>
<div class="grid-container">
  <div class='student-cards'>
  <%= link_to new_classroom_student_path(Classroom.last) do %>
  <div class="student-card" style="background-image: url(<%= image_path 'background4.png' %>)">
    <i class="fa fa-plus" id="plus-sign"></i>
  </div>
  <% end %>
    <% @students.each do |student| %>
      <div class="student-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path student.photo.key, height: 300, crop: :fill %>')">
        <h2><strong><%= link_to student.first_name, student_path(student), class:'link' %></strong></h2>
      </div>
    <% end %>
  </div>
</div>

app/views/students/new.html.erb
<div class="container">
  <h1> Add new Student </h1>
  <div class="container-form">
    <%= simple_form_for [@classroom, @student] do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :date_of_birth %>
      <%= f.input :coins %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create", class: "btn btn-danger" %>
    <% end %>
</div>

app/views/students/show.html.erb
<h1><%= @student.first_name %><%= " " %><%= @student.last_name %></h1>
<div class="student-show" style="width: 650px;margin: auto;">
<div class="d-flex" style="justify-content: center;margin-top: 15px">
<p id="student-coins"><%= image_tag ("Tiles/coin_shop_3.png"), class: "coins-row" %><%= @student.coins%></p>
<p id="student-birth"><%= image_tag ("birthday_cake.png"), class: "cake-row" %><%= @student.date_of_birth.strftime('%d %b %Y') %></p>
</div>
<div class="achievements">
<h1 style="font-size: 40px;justify-content: space-around;"><%= image_tag "10_start.png", class: "achiev-star"%> Achievements <%= image_tag "10_start.png", class: "achiev-star"%></h1>
  <% if @my_missions_completed.empty? %>
    <h2 style="style=padding: 10px;font-size: 20px;"> Sorry no achievements ... yet 🤓 </h2>
</div>
  <% else %>
  <div class="missions-cards" style="margin-bottom: -30px;">
    <% @my_missions_completed.each do |m| %>
    <div class="student-mission">
      <div class="achiev-card">
        <%= image_tag "gold_trophy3.png", class: "trophy"%>
          <p><%= m.name.upcase %></p>
      </div>
      <div class="description d-none" data-insert-in-list-target="description">
        <p class ="mission_description"><%= m.description %></p>
      </div>
      </div>
    <% end %>
    <% end %>
    </div>
  </div>
</div>