config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'classrooms#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :missions, only: %i[edit update destroy] do
    resources :mission_setups, only: %i[create index update]
  end

  resources :classrooms, only: [:show] do
    resources :students, only: %i[index new create]
    resources :missions, only: %i[new create index]
  end

  resources :mission_setups do
    collection do
      match "update_collection", via: %i[put patch]
    end
  end

  resources :students, only: %i[show update]
  resources :rewards, only: %i[index show new create destroy] do
    resources :reward_transactions, only: %i[create show index]
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = Reward.all
  end

  def show
    @reward = Reward.find(params[:id])
    @reward_transaction = RewardTransaction.new
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    @reward.user = current_user
    if @reward.save
      redirect_to rewards_path(@rewards)
    else
      render :new
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    redirect_to rewards_path(@rewards)
  end

  private

  def reward_params
    params.require(:reward).permit(:title, :description, :price, :photo)
  end
end

app/views/rewards/index.html.erb
<h1> Rewards</h1>
<%= link_to "+", new_reward_path(@reward), class:"btn-plus" %>
<div class="grid-container">
  <div class='student-cards'>
    <% @rewards.each do |reward| %>
      <div class="student-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path reward.photo.key, height: 300, crop: :fill %>')">
        <div class="info-card">
          <h2><strong><%= link_to reward.title, reward_path(reward), class:'link' %></strong></h2>
        </div>
        <div class="trash">
          <%= link_to reward_path(reward), method: :delete do %>
            <i class="fas fa-trash" ></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rewards/new.html.erb
<div class="container">
  <h1> Add new Reward </h1>
  <div class="container-form">
    <%= simple_form_for [@reward] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/rewards/show.html.erb
<div id="back">
  <%= link_to rewards_path do %>
    <%= image_tag("big_arrow.png") %>
  <% end %>
</div>
<div class="container-form">
  <h1> Reward</h1>
  <div class="student-show">
    <p><%= @reward.title %></p>
    <h3><%= @reward.description %></h3>
    <h3><%= @reward.price %><%= " " %><%= image_tag ("Tiles/coin_shop_3.png"), class: "coins-row" %></h3>
  </div>
  <%= simple_form_for([@reward, @reward_transaction]) do |f| %>
    <%= f.association :student, value: :name %>
    <%= f.submit "Claim Reward!", class: "claim-reward" %>
  <% end %>
</div>