config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'classrooms#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :missions, only: %i[edit update destroy] do
    resources :mission_setups, only: %i[create index update]
  end

  resources :classrooms, only: [:show] do
    resources :students, only: %i[index new create]
    resources :missions, only: %i[new create index]
  end

  resources :mission_setups do
    collection do
      match "update_collection", via: %i[put patch]
    end
  end

  resources :students, only: %i[show update]
  resources :rewards, only: %i[index show new create destroy] do
    resources :reward_transactions, only: %i[create show index]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_mission_card.html.erb
<div class='mission-card'>
  <%= image_tag "rocket.png", class: "mission-photo" %>
  <strong> <%= mission.name %> </strong>
    <div class="card-mission-bottom">
      <div class="card-mission-bottom-left">
        <p> <%= mission.coins %> <i class="fa fa-coins"></i> </p>
      </div>
        <div class="card-bottom-right">
            <a href="url"><i class="fas fa-play"></i></a>
            <a href="url"><i class="fas fa-info"></i></a>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-page">
    <div class="d-flex justify-content-between">
      <div class="logo-div">
        <%= link_to root_path ,class: "navbar-brand" do %>
          <%= image_tag "logo.png", id: "logo"%>
        <% end %>
          <%= image_tag "gamify.png", id:"gamify-logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
       </div>
      <ul class="navbar-nav">
          <% if user_signed_in? %>
          <div class="nav-icons">
          <div class="icon">
            <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
            <lottie-player src="https://assets8.lottiefiles.com/packages/lf20_ei7frqcx.json"  background="transparent"  speed="1"  style="width: 50px; height: 50px;" loop autoplay  ></lottie-player>
          </div>
              <%= link_to "Home", root_path, class: "nav-link" %>
          </div>
          <div class="nav-icons">
          <div class="icon" id="class-icon">
            <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
            <lottie-player src="https://assets6.lottiefiles.com/private_files/lf30_irme4vjh.json"  background="transparent"  speed="1"  style="width: 30px; height: 30px;" loop autoplay  ></lottie-player>
          </div>
              <%= link_to "Rewards", rewards_path(@rewards), class: "nav-link" %>
          </div>
          <div class="nav-icons">
          <div class="icon" id="class-icon">
              <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
              <lottie-player src="https://assets2.lottiefiles.com/private_files/lf30_IHXuk5.json"  background="transparent" speed="1"  style="width: 30px; height: 30px" loop  autoplay ></lottie-player>
            </div>
                <%= link_to "Classroom", classroom_students_path(@classroom), class: "nav-link" %>
          </div>
          <div class="nav-icons">
          <div class="icon">
            <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
            <lottie-player src="https://assets10.lottiefiles.com/packages/lf20_evrce8mt.json"  background="transparent"  speed="1"  style="width: 45px; height: 45px;" loop autoplay  ></lottie-player>
          </div>
              <%= link_to "Missions", classroom_missions_path(@classroom), class: "nav-link" %>
          </div>
            <li id="nav-teacher">
              <%= image_tag "https://st.depositphotos.com/2400497/2931/v/600/depositphotos_29310763-stock-illustration-cartoon-professor.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_ranking.html.erb
<div class="leaderboard">
  <% students = Classroom.last.students  %>
  <% students_sorted = students.sort_by { |s| -s.coins}   %>
  <%  students_sorted.each_with_index do |student, index| %>
    <div class = "row-leaderboard mt-4">
      <%= image_tag (cl_image_path student.photo.key), class: "ava-row" %>
      <p class = "name-text"><%=" #{index + 1}"%> &nbsp; &nbsp; <%= "#{student.first_name}" %></p>
      <div>
        <p class="coin-text" id="<%=student.id %>" data-leaderboard-target="coins"><%= student.coins %></p>
        <%= image_tag ("Tiles/coin_shop_3.png"), class: "coins-row" %>
      </div>
      <div>
          <%= link_to student_path(student, value:"add"), method: :patch, id: student.id, data: { action: "click->leaderboard#add" }, class: "add-button" do %>
          <%= image_tag "1_coins.png", :class => "add-button d-flex"%>
          <% end %>
          <%= link_to student_path(student, value:"subtract"), method: :patch, id: student.id, data: { action: "click->leaderboard#subtract" }, class: "subtract-button" do %>
          <%= image_tag "coins.png", :class => "add-button d-flex"%>
          <% end %>
        </div>
    </div>
  <% end %>
</div>

app/views/shared/_row_leaderboard.html.erb
<div class = "row-leaderboard">
  <% @students.each do |student| %>
    <%= image_tag (cl_image_path student.photo.key), class: "ava-row" %>
  <% end %>
  <p class = "name-text">Student Name</p>
  <div>
    <p class="coin-text">200</p>
    <%= image_tag ("Tiles/coin_shop_3.png"), class: "coins-row" %>
  </div>
</div>

app/views/shared/_row_mission.html.erb
<div class = "row-leaderboard">
  <%= image_tag ("ava/ava-1.png"), class: "ava-row" %>
  <p class = "name-text">Student Name</p>
  <div>
    <%= image_tag ("100_icons/little/8_ok.png"), class: "right-worng-row" %>
  </div>
</div>