config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'classrooms#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :missions, only: %i[edit update destroy] do
    resources :mission_setups, only: %i[create index update]
  end

  resources :classrooms, only: [:show] do
    resources :students, only: %i[index new create]
    resources :missions, only: %i[new create index]
  end

  resources :mission_setups do
    collection do
      match "update_collection", via: %i[put patch]
    end
  end

  resources :students, only: %i[show update]
  resources :rewards, only: %i[index show new create destroy] do
    resources :reward_transactions, only: %i[create show index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# <title>Gamify - Engage your students</title> %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
    <% if current_page?(root_path) %>
    <body style="background-image: url(<%= asset_path '1.png' %>);">
    <% elsif current_user && current_page?(classroom_students_path(current_user.classroom))%>
    <body style="background-image: url(<%= asset_path '2.png' %>);">
    <% elsif current_user && current_page?(classroom_missions_path(current_user.classroom))%>
    <body style="background-image: url(<%= asset_path '4.png' %>);">
    <%##elsif current_user && current_page?(students_path)%>
    <%# <body style="background-image: url(<%= asset_path '4.png' %>
    <% else %>
    <body style="background-image: url(<%= asset_path '1.png' %>);">
    <% end %>
      <%= render 'shared/navbar', class: @classroom %>
      <div class="container-page">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </body>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </div>
</html>